#---意味着开始i一个新的文档，需要用load_all
---
common_datas: 
  home_url: http://120.78.128.25:8765/Index/login.html
  user_data: 13760246701
  user_pwd: python
  window_handles_list: []
---   
testlogin_datas: 
  login_success: 
    - 
      user_name: 13760246701
      user_pwd: python
      msg: '我的帐户[小蜜蜂96027837]'
  login_fail_null: 
    -
      user_name: 
      user_pwd: python
      msg: '请输入手机号'
    -
      user_name: 18684720553
      user_pwd: 
      msg: '请输入密码'
    -
      user_name: 
      user_pwd: 
      msg: '请输入手机号'
    -
      user_name: 186847
      user_pwd: python
      msg: '请输入正确的手机号'
    -
      user_name: 186847205531
      user_pwd: python
      msg: '请输入正确的手机号'

  login_fail_wrong: 
    -
      user_name: 17312783975
      user_pwd: python
      msg: '此账号没有经过授权，请联系管理员!'
    -
      user_name: 13760246701
      user_pwd: pppp
      msg: 帐号或密码错误
---
invest_datas: 
  invest_success: 
    - 
      invest_ammount: 100
      msg: '投标成功'
  invest_wrong: 
    -
      invest_ammount: 0
      msg: '请正确填写投标金额'
    - 
      invest_ammount: 110
      msg: '投标金额必须为100的倍数'
    - 
      invest_ammount: 550000
      msg: '购买标的金额不能大于标总金额'
    - 
      invest_ammount: 999999999999990
      msg: '投标金额大于可用金额'
  invest_not_multiple_of_10: 
    - 
      invest_ammount: 15
      msg: '请输入10的整数倍'